import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {JSDOM} from 'jsdom';
import * as core from '../dist/core.js';
const html=await readFile(new URL('../dist/ui.html',import.meta.url),'utf8');
const source=(await readFile(new URL('../dist/ui.js',import.meta.url),'utf8')).replace(/import \{([^}]+)\} from '\.\/core.js';/, 'const {$1} = core;');
const w={currency:23,code:'CNY',symbol:'¥',minimum:1,increment:1,steamRate:.05,publisherRate:.1};
test('UI switches all prices atomically and sends canonical proceeds to draft and review',async()=>{
 const dom=new JSDOM(html,{url:'chrome-extension://test/ui.html#test'}), doc=dom.window.document;
 const context={appid:'730',contextid:'2',name:'CS2',count:2,publisherRate:.1};
 const inventory=core.mergePage(undefined,{records:['A','B'].map((name,i)=>({assetid:String(i+1),hashName:name,name,type:'Case',icon:'',amount:3,commodity:true,marketable:true})),total:2,more:false,cursor:''},context,Date.now());
 const session={bootstrap:{account:'76561198000000000',wallet:w,contexts:[context]},inventory,draft:[],references:{}};
 const calls=[]; const chrome={runtime:{sendMessage:async(m)=>{calls.push(m);return {ok:true,data:m.type==='review'?core.buildReview(inventory,m.rows,session.bootstrap.account,w,{},Date.now(),'r'):m.type==='state'?session:true};}}};
 const AsyncFunction=Object.getPrototypeOf(async function(){}).constructor;
 await new AsyncFunction('core','document','location','chrome','setInterval','confirm',source)(core,doc,dom.window.location,chrome,()=>0,()=>true);
 const settle=()=>new Promise(r=>setImmediate(r)); await settle();
 const event=(el,type,value)=>{if(value!==undefined)el.value=value;el.dispatchEvent(new dom.window.Event(type,{bubbles:true}));};
 const get=id=>doc.getElementById(id), price=name=>doc.querySelector(`input[aria-label="${name}每件${get('price-mode').value==='paid'?'买方支付价':'到手价'}"]`);
 get('select-all').click();event(price('A'),'input','9.96');event(price('B'),'input','1.00');
 event(get('search'),'input','A');event(get('price-mode'),'change','paid');assert.equal(price('A').value,'11.44');
 event(get('search'),'input','');assert.equal(price('B').value,'1.15');
 event(price('B'),'input','bad');event(get('price-mode'),'change','receive');assert.equal(get('price-mode').value,'paid');assert.equal(price('A').value,'11.44');
 event(price('B'),'input','0.01');assert.equal(get('review').disabled,true);
 event(price('B'),'input','0.22');assert.match(price('B').parentElement.textContent,/取整后买方支付 ¥0.21/);
 event(get('price-mode'),'change','receive');assert.equal(price('A').value,'9.96');assert.equal(price('B').value,'0.19');
 event(get('price-mode'),'change','paid');assert.equal(price('B').value,'0.21');
 get('save').click();await settle();assert.deepEqual(calls.find(m=>m.type==='draft').rows.map(r=>r.receive),[996,19]);
 get('review').click();await settle();assert.match(get('review-total').textContent,/手续费合计 ¥1.50/);assert.match(get('review-items').textContent,/¥1.48/);assert.equal(get('review-items').children[0].children.length,7);
 dom.window.close();
});
